# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    #driver: "gd"

    filter_sets:
        thumb_bandeau_college:
            quality: 75
            filters:
                thumbnail:
                    size: [ 1132, 250 ]
                    mode: outbond

        thumb_logo_college:
            quality: 75
            filters:
                thumbnail:
                    size: [200, 152]
                    mode: outbond

        thumb_card_college:
            quality: 75
            filters:
                thumbnail:
                    size: [ 314, 240 ]
                    mode: outbond

        thumb_img_article:
            quality: 75
            filters:
                thumbnail:
                    size: [ 280, 210 ]
                    mode: outbond